//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItchGamingWiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameReview
    {
        public int ReviewId { get; set; }
        public int GameId { get; set; }
        public System.Guid UserId { get; set; }
        public string ContentReview { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
