//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItchGamingWiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameReviews = new HashSet<GameReview>();
        }
    
        public int GameId { get; set; }
        public string GameName { get; set; }
        public string GameType { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public string Developer { get; set; }
        public string Publisher { get; set; }
        public string LinkGame { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameReview> GameReviews { get; set; }
    }
}
