//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItchGamingWiki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItchGamingWikiEntities : DbContext
    {
        public ItchGamingWikiEntities()
            : base("name=ItchGamingWikiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameReview> GameReviews { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<SYSGroupGame> SYSGroupGames { get; set; }
        public virtual DbSet<SYSGroupRole> SYSGroupRoles { get; set; }
        public virtual DbSet<SYSGroupUser> SYSGroupUsers { get; set; }
        public virtual DbSet<SYSMenu> SYSMenus { get; set; }
        public virtual DbSet<SYSUser> SYSUsers { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRoles { get; set; }
    }
}
