//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItchGamingWiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSGroupUser
    {
        public decimal Id { get; set; }
        public System.Guid GroupId { get; set; }
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public Nullable<int> Enable { get; set; }
    
        public virtual SYSGroupGame SYSGroupGame { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
