//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItchGamingWiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUserRole
    {
        public decimal RoleId { get; set; }
        public System.Guid UserId { get; set; }
        public string RoleName { get; set; }
        public int MenuId { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> RoleView { get; set; }
        public Nullable<int> RoleAdd { get; set; }
        public Nullable<int> RoleEdit { get; set; }
        public Nullable<int> RoleImport { get; set; }
        public Nullable<int> RoleExport { get; set; }
        public Nullable<int> RolePrint { get; set; }
        public System.Guid GroupId { get; set; }
        public Nullable<int> RoleDelete { get; set; }
    
        public virtual SYSGroupGame SYSGroupGame { get; set; }
        public virtual SYSMenu SYSMenu { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
